version: '3.8'

services:
  apache:
    image: httpd:2.4
    volumes:
      - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
    networks:
      - web_network
  tomcat:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - web_network
    depends_on:
      - apache
networks:
  web_network:
    driver: bridge 
